-- V1: Initial Schema (Sync with BigDecimal/Numeric)
-- Standardizing all decimal fields to NUMERIC for Java BigDecimal compatibility

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'CLIENT',
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE coach (
    user_id BIGINT PRIMARY KEY,
    full_name VARCHAR(255), -- Added full_name
    bio TEXT,
    specialization VARCHAR(255),
    weekly_fee NUMERIC(19,2),
    currency VARCHAR(10) DEFAULT 'TRY',
    is_verified BOOLEAN DEFAULT FALSE,
    profile_photo_url VARCHAR(500),
    cover_photo_url VARCHAR(500),
    date_of_birth DATE,
    height_cm INTEGER,
    weight_kg NUMERIC(19,2),
    show_metrics BOOLEAN DEFAULT TRUE,
    instagram_url VARCHAR(255),
    website_url VARCHAR(255),
    CONSTRAINT fk_coach_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

CREATE TABLE client (
    user_id BIGINT PRIMARY KEY,
    coach_id BIGINT,
    full_name VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(50),
    height_cm INTEGER,
    weight_kg NUMERIC(19,2),
    goal VARCHAR(255),
    activity_level VARCHAR(255),
    profile_photo_url VARCHAR(500),
    cover_photo_url VARCHAR(500),
    bio TEXT,
    show_age BOOLEAN DEFAULT TRUE,
    show_height BOOLEAN DEFAULT TRUE,
    show_weight BOOLEAN DEFAULT TRUE,
    selected_meal_plan_id BIGINT,
    CONSTRAINT fk_client_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_client_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id)
);

CREATE TABLE exercise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    muscle_group VARCHAR(255),
    description TEXT
);
