-- V22: Nutrition Module Expansion - Food Override Support

-- Ensure Food table has all requested macro fields (Requirement 4)
-- Existing table already has most, but we ensure consistency and types.
-- Requirement: kalori, karbonhidrat, yag, protein, fiber, seker, yag, doymus yag, coklu doymamis yag, tekli doymamis yag, kolestrol, sodyum, potasyum

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='food' AND column_name='brand') THEN
        ALTER TABLE food ADD COLUMN brand VARCHAR(255);
    END IF;
END $$;

-- Table for User Personal Food Overrides (Requirement 9)
CREATE TABLE user_food_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,
    calories NUMERIC(12,4),
    protein NUMERIC(12,4),
    carbs NUMERIC(12,4),
    fat NUMERIC(12,4),
    sugar NUMERIC(12,4),
    fiber NUMERIC(12,4),
    sodium NUMERIC(12,4),
    cholesterol NUMERIC(12,4),
    potassium NUMERIC(12,4),
    sat_fat NUMERIC(12,4),
    trans_fat NUMERIC(12,4),
    mono_fat NUMERIC(12,4),
    poly_fat NUMERIC(12,4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_override_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_override_food FOREIGN KEY (food_id) REFERENCES food(id),
    CONSTRAINT unique_user_food_override UNIQUE (user_id, food_id)
);

-- Index for faster food searches
CREATE INDEX idx_food_name ON food(name);
CREATE INDEX idx_override_user_food ON user_food_override(user_id, food_id);
