-- V23: Nutrition Module - Diet Programs and Meals Structure

-- Diet Program table (Requirement 5 & 6)
CREATE TABLE diet_program (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    coach_id BIGINT,
    name VARCHAR(255) NOT NULL,
    is_main BOOLEAN DEFAULT FALSE,
    source VARCHAR(20) NOT NULL, -- 'CLIENT' or 'COACH'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_diet_owner FOREIGN KEY (owner_id) REFERENCES app_user(id),
    CONSTRAINT fk_diet_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id)
);

-- Meal table (Requirement 3)
CREATE TABLE meal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet_program_id BIGINT NOT NULL,
    meal_type VARCHAR(50) NOT NULL, -- 'BREAKFAST', 'LUNCH', 'DINNER', 'OTHER'
    order_index INTEGER DEFAULT 0,
    CONSTRAINT fk_meal_program FOREIGN KEY (diet_program_id) REFERENCES diet_program(id) ON DELETE CASCADE
);

-- Meal Ingredient table (Relationship between Meal and Food)
CREATE TABLE meal_ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,
    amount NUMERIC(10,2) NOT NULL, -- e.g. 150g
    note VARCHAR(255),
    CONSTRAINT fk_ingredient_meal FOREIGN KEY (meal_id) REFERENCES meal(id) ON DELETE CASCADE,
    CONSTRAINT fk_ingredient_food FOREIGN KEY (food_id) REFERENCES food(id)
);

-- Ensure only one main program per user
CREATE UNIQUE INDEX idx_unique_main_diet ON diet_program (owner_id) WHERE (is_main = TRUE);
