-- V24: Nutrition Module - Meal Templates

-- Meal Template table (Requirement 8-C)
CREATE TABLE meal_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_template_owner FOREIGN KEY (owner_id) REFERENCES app_user(id)
);

-- Meal Template Ingredient table
CREATE TABLE meal_template_ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_template_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_temp_ing_template FOREIGN KEY (meal_template_id) REFERENCES meal_template(id) ON DELETE CASCADE,
    CONSTRAINT fk_temp_ing_food FOREIGN KEY (food_id) REFERENCES food(id)
);
