-- V25: Nutrition Module - Water Intake and Macro Targets

-- Add target fields to diet_program
ALTER TABLE diet_program ADD COLUMN target_calories NUMERIC(10,2) DEFAULT 0;
ALTER TABLE diet_program ADD COLUMN target_protein NUMERIC(10,2) DEFAULT 0;
ALTER TABLE diet_program ADD COLUMN target_carbs NUMERIC(10,2) DEFAULT 0;
ALTER TABLE diet_program ADD COLUMN target_fat NUMERIC(10,2) DEFAULT 0;

-- Water Intake table
CREATE TABLE water_intake (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount_ml INTEGER NOT NULL, -- ml cinsinden (örn: 250ml = 1 bardak)
    intake_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_water_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

-- Index for date queries
CREATE INDEX idx_water_user_date ON water_intake(user_id, intake_date);
