-- V27: Advanced Water Tracking Enhancements
-- Hedeflerin tarihçesini tutmak için tablo
CREATE TABLE water_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    target_ml INTEGER NOT NULL,
    valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to TIMESTAMP, -- NULL ise şu anki geçerli hedef
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_water_target_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

-- Kullanıcının özel bardaklarını tutmak için tablo (Maks 3 adet uygulama tarafında kontrol edilecek)
CREATE TABLE custom_glasses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    size_ml INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_custom_glass_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

-- Index'ler
CREATE INDEX idx_water_targets_user ON water_targets(user_id);
CREATE INDEX idx_custom_glasses_user ON custom_glasses(user_id);
