-- V2: Training and Nutrition Modules (Detailed Macros from Backup)

-- Training Module
CREATE TABLE workout_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    coach_id BIGINT,
    workout_date DATE NOT NULL,
    title VARCHAR(255),
    status VARCHAR(50) DEFAULT 'PLANNED',
    CONSTRAINT fk_workoutday_client FOREIGN KEY (client_id) REFERENCES client(user_id),
    CONSTRAINT fk_workoutday_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id)
);

CREATE TABLE workout_exercise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_day_id BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    order_index INTEGER DEFAULT 1,
    target_sets INTEGER,
    target_reps INTEGER,
    to_failure BOOLEAN DEFAULT FALSE,
    note VARCHAR(255),
    CONSTRAINT fk_workoutexercise_workoutday FOREIGN KEY (workout_day_id) REFERENCES workout_day(id) ON DELETE CASCADE,
    CONSTRAINT fk_workoutexercise_exercise FOREIGN KEY (exercise_id) REFERENCES exercise(id)
);

CREATE TABLE workout_exercise_set_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_exercise_id BIGINT NOT NULL,
    set_number INTEGER NOT NULL,
    actual_reps INTEGER,
    actual_weight NUMERIC,
    to_failure BOOLEAN DEFAULT FALSE,
    logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_setlog_workoutexercise FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercise(id) ON DELETE CASCADE
);

-- Nutrition Module (Full Macro Support)
CREATE TABLE food (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    category VARCHAR(100),
    default_unit VARCHAR(20) NOT NULL,
    default_amount NUMERIC(10,2) NOT NULL,
    calories NUMERIC(12,4),
    protein NUMERIC(12,4),
    carbs NUMERIC(12,4),
    fat NUMERIC(12,4),
    sugar NUMERIC(12,4),
    fiber NUMERIC(12,4),
    sodium NUMERIC(12,4),
    cholesterol NUMERIC(12,4),
    potassium NUMERIC(12,4),
    sat_fat NUMERIC(12,4),
    trans_fat NUMERIC(12,4),
    mono_fat NUMERIC(12,4),
    poly_fat NUMERIC(12,4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    creator_id BIGINT,
    is_global BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE meal_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    coach_id BIGINT,
    planned_datetime TIMESTAMP,
    title VARCHAR(255),
    description TEXT,
    target_calories NUMERIC,
    target_protein NUMERIC,
    target_carbs NUMERIC,
    target_fat NUMERIC,
    target_sugar NUMERIC(12,4),
    target_fiber NUMERIC(12,4),
    target_sodium NUMERIC(12,4),
    target_cholesterol NUMERIC(12,4),
    target_potassium NUMERIC(12,4),
    target_sat_fat NUMERIC(12,4),
    target_trans_fat NUMERIC(12,4),
    target_mono_fat NUMERIC(12,4),
    target_poly_fat NUMERIC(12,4),
    CONSTRAINT fk_mealplan_client FOREIGN KEY (client_id) REFERENCES client(user_id),
    CONSTRAINT fk_mealplan_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id)
);

CREATE TABLE meal_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    meal_plan_id BIGINT,
    taken_datetime TIMESTAMP,
    photo_url VARCHAR(500),
    calories NUMERIC,
    protein NUMERIC,
    carbs NUMERIC,
    fat NUMERIC,
    notes VARCHAR(255),
    sugar NUMERIC(12,4),
    fiber NUMERIC(12,4),
    sodium NUMERIC(12,4),
    cholesterol NUMERIC(12,4),
    potassium NUMERIC(12,4),
    sat_fat NUMERIC(12,4),
    trans_fat NUMERIC(12,4),
    mono_fat NUMERIC(12,4),
    poly_fat NUMERIC(12,4),
    CONSTRAINT fk_mealentry_client FOREIGN KEY (client_id) REFERENCES client(user_id)
);

CREATE TABLE meal_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_entry_id BIGINT,
    food_id BIGINT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    unit_override VARCHAR(20),
    note VARCHAR(255),
    calories NUMERIC(12,4),
    protein NUMERIC(12,4),
    carbs NUMERIC(12,4),
    fat NUMERIC(12,4),
    CONSTRAINT fk_mealitem_entry FOREIGN KEY (meal_entry_id) REFERENCES meal_entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_mealitem_food FOREIGN KEY (food_id) REFERENCES food(id)
);
