-- V25: Nutrition Module - Diet 7 Days Structure

-- Temiz Başlangıç (Eski test verilerini temizle ki migration patlamasın)
TRUNCATE TABLE meal_ingredient, meal, diet_program CASCADE;

CREATE TABLE diet_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet_program_id BIGINT NOT NULL,
    day_order INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_dietday_program FOREIGN KEY (diet_program_id) REFERENCES diet_program(id) ON DELETE CASCADE
);

ALTER TABLE meal ADD COLUMN diet_day_id BIGINT;
ALTER TABLE meal DROP CONSTRAINT fk_meal_program;
ALTER TABLE meal DROP COLUMN diet_program_id;

-- Geriye dönük bağı kur
ALTER TABLE meal ADD CONSTRAINT fk_meal_day FOREIGN KEY (diet_day_id) REFERENCES diet_day(id) ON DELETE CASCADE;
ALTER TABLE meal ALTER COLUMN diet_day_id SET NOT NULL;
