-- V32: Add micro-nutrients columns to diet_program and meal_item

-- Diet Program table additions
ALTER TABLE diet_program ADD COLUMN IF NOT EXISTS target_sugar NUMERIC(12,4) DEFAULT 0;
ALTER TABLE diet_program ADD COLUMN IF NOT EXISTS target_fiber NUMERIC(12,4) DEFAULT 0;
ALTER TABLE diet_program ADD COLUMN IF NOT EXISTS target_sodium NUMERIC(12,4) DEFAULT 0;
ALTER TABLE diet_program ADD COLUMN IF NOT EXISTS target_cholesterol NUMERIC(12,4) DEFAULT 0;
ALTER TABLE diet_program ADD COLUMN IF NOT EXISTS target_potassium NUMERIC(12,4) DEFAULT 0;

-- Meal Item table additions
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS sugar NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS fiber NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS sodium NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS cholesterol NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS potassium NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS sat_fat NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS trans_fat NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS mono_fat NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_item ADD COLUMN IF NOT EXISTS poly_fat NUMERIC(12,4) DEFAULT 0;
