-- V35: Nutrition Module - Recipes
CREATE TABLE recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    instructions TEXT,
    category VARCHAR(100),
    image_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE recipe_ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_recipe_ing_recipe FOREIGN KEY (recipe_id) REFERENCES recipe(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ing_food FOREIGN KEY (food_id) REFERENCES food(id)
);
