-- V38: User Recipes and Recipe Logging
-- MealItem artık bir besin (food) yerine bir tarif (recipe) de içerebilir.
ALTER TABLE meal_item ALTER COLUMN food_id DROP NOT NULL;
ALTER TABLE meal_item ADD COLUMN recipe_id BIGINT;
ALTER TABLE meal_item ADD COLUMN user_recipe_id BIGINT;

ALTER TABLE meal_item ADD CONSTRAINT fk_meal_item_recipe FOREIGN KEY (recipe_id) REFERENCES recipe(id);

-- Kullanıcıya özel tarifler tablosu
CREATE TABLE user_recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_recipe_id BIGINT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    instructions TEXT,
    category VARCHAR(100),
    image_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_recipe_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_user_recipe_original FOREIGN KEY (original_recipe_id) REFERENCES recipe(id) ON DELETE SET NULL
);

ALTER TABLE meal_item ADD CONSTRAINT fk_meal_item_user_recipe FOREIGN KEY (user_recipe_id) REFERENCES user_recipe(id);

-- Kullanıcıya özel tarifin malzemeleri
CREATE TABLE user_recipe_ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_recipe_id BIGINT NOT NULL,
    food_id BIGINT NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_user_recipe_ing_recipe FOREIGN KEY (user_recipe_id) REFERENCES user_recipe(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_recipe_ing_food FOREIGN KEY (food_id) REFERENCES food(id)
);

-- Bir MealItem ya food_id, ya recipe_id ya da user_recipe_id içermelidir (sadece biri)
ALTER TABLE meal_item ADD CONSTRAINT ck_meal_item_target CHECK (
    (food_id IS NOT NULL AND recipe_id IS NULL AND user_recipe_id IS NULL) OR
    (food_id IS NULL AND recipe_id IS NOT NULL AND user_recipe_id IS NULL) OR
    (food_id IS NULL AND recipe_id IS NULL AND user_recipe_id IS NOT NULL)
);
