-- V3: Progress, Social, Billing and Certificates (Comprehensive Backup Sync)

-- Progress and Media
CREATE TABLE client_progress_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    caption VARCHAR(500),
    is_public BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_progress_photo_client FOREIGN KEY (client_id) REFERENCES client(user_id) ON DELETE CASCADE
);

-- Messaging System
CREATE TABLE conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    blocked_by_user_id BIGINT,
    blocked_at TIMESTAMP,
    blocked_reason VARCHAR(500),
    CONSTRAINT fk_conv_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id),
    CONSTRAINT fk_conv_client FOREIGN KEY (client_id) REFERENCES client(user_id)
);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_user_id BIGINT NOT NULL,
    content TEXT,
    message_type VARCHAR(50) DEFAULT 'TEXT',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN DEFAULT FALSE,
    deleted_for_sender BOOLEAN DEFAULT FALSE,
    deleted_for_receiver BOOLEAN DEFAULT FALSE,
    deleted_globally BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_msg_conv FOREIGN KEY (conversation_id) REFERENCES conversation(id) ON DELETE CASCADE,
    CONSTRAINT fk_msg_sender FOREIGN KEY (sender_user_id) REFERENCES app_user(id)
);

-- Coach Specifics
CREATE TABLE coach_certificate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id BIGINT NOT NULL,
    title VARCHAR(255),
    image_url VARCHAR(500),
    issued_at DATE,
    CONSTRAINT fk_cert_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id) ON DELETE CASCADE
);

CREATE TABLE coach_rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    rating INTEGER,
    comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rating_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id),
    CONSTRAINT fk_rating_client FOREIGN KEY (client_id) REFERENCES client(user_id)
);

-- Billing and Subscription
CREATE TABLE subscription_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    weekly_price NUMERIC,
    currency VARCHAR(10) DEFAULT 'TRY',
    billing_period VARCHAR(50) DEFAULT 'WEEKLY',
    coach_id BIGINT,
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_plan_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id)
);

CREATE TABLE client_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    subscription_plan_id BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    price_override NUMERIC,
    created_by_coach_id BIGINT,
    CONSTRAINT fk_sub_client FOREIGN KEY (client_id) REFERENCES client(user_id),
    CONSTRAINT fk_sub_plan FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan(id)
);
