-- V43: Add macro and micro nutrients to meal_ingredient table
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS calories NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS protein NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS carbs NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS fat NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS sugar NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS fiber NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS sodium NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS cholesterol NUMERIC(12,4) DEFAULT 0;
ALTER TABLE meal_ingredient ADD COLUMN IF NOT EXISTS potassium NUMERIC(12,4) DEFAULT 0;
