-- V49: Profile URL'leri ve ek alanların eklenmesi
ALTER TABLE client ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(255);
ALTER TABLE client ADD COLUMN IF NOT EXISTS website_url VARCHAR(255);
ALTER TABLE client ADD COLUMN IF NOT EXISTS show_age BOOLEAN DEFAULT TRUE;
ALTER TABLE client ADD COLUMN IF NOT EXISTS show_height BOOLEAN DEFAULT TRUE;
ALTER TABLE client ADD COLUMN IF NOT EXISTS show_weight BOOLEAN DEFAULT TRUE;

ALTER TABLE coach ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(500);
ALTER TABLE coach ADD COLUMN IF NOT EXISTS website_url VARCHAR(500);
ALTER TABLE coach ADD COLUMN IF NOT EXISTS height_cm INTEGER;
ALTER TABLE coach ADD COLUMN IF NOT EXISTS weight_kg DECIMAL(5,2);
ALTER TABLE coach ADD COLUMN IF NOT EXISTS show_subscriber_count BOOLEAN DEFAULT FALSE;
