-- V5: Pairing Requests for Coach-Client Matching

CREATE TABLE pairing_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    coach_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pairing_client FOREIGN KEY (client_id) REFERENCES client(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_pairing_coach FOREIGN KEY (coach_id) REFERENCES coach(user_id) ON DELETE CASCADE,
    CONSTRAINT unique_pairing_request UNIQUE (client_id, coach_id, status) -- Prevents multiple pending requests for the same pair
);

-- Index for faster lookups
CREATE INDEX idx_pairing_request_coach ON pairing_request(coach_id);
CREATE INDEX idx_pairing_request_client ON pairing_request(client_id);
