-- V61: Finans ve Ödeme Modülü Tabloları

DROP TABLE IF EXISTS client_subscription CASCADE;
DROP TABLE IF EXISTS subscription_plan CASCADE;

CREATE TABLE subscription_package (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    duration_days INTEGER NOT NULL,
    coach_id BIGINT,
    description TEXT,
    CONSTRAINT fk_package_coach FOREIGN KEY (coach_id) REFERENCES app_user(id) ON DELETE SET NULL
);

CREATE TABLE client_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    coach_id BIGINT,
    package_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_sub_client FOREIGN KEY (client_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_sub_coach FOREIGN KEY (coach_id) REFERENCES app_user(id) ON DELETE SET NULL,
    CONSTRAINT fk_sub_package FOREIGN KEY (package_id) REFERENCES subscription_package(id) ON DELETE RESTRICT
);

CREATE TABLE payment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    transaction_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tx_client FOREIGN KEY (client_id) REFERENCES app_user(id) ON DELETE CASCADE
);

INSERT INTO subscription_package (name, price, duration_days, coach_id, description) VALUES
('1 Aylık Standart Koçluk', 500.00, 30, NULL, 'Temel antrenman ve beslenme desteği sağlayan 1 aylık koçluk paketi.'),
('3 Aylık Premium Koçluk', 1200.00, 90, NULL, '7/24 iletişim ve detaylı form analizi içeren avantajlı 3 aylık koçluk paketi.'),
('6 Aylık VIP Koçluk', 2000.00, 180, NULL, 'Kapsamlı gelişim takibi ve birebir görüntülü görüşme desteği sunan 6 aylık VIP koçluk paketi.');
