-- V63: Checkout Sipariş (Order) Tablosunun Oluşturulması
CREATE TABLE checkout_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    package_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    checkout_session_id VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_client FOREIGN KEY (client_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_package FOREIGN KEY (package_id) REFERENCES subscription_package(id) ON DELETE RESTRICT
);
