-- L1: Bildirim token'i tek alanda tutuluyordu (app_user.fcm_token).
-- Sonuclari:
--   1) Kullanici ikinci cihazdan girince token uzerine yaziliyor ve BIRINCI CIHAZ
--      bildirim almayi birakiyordu. Telefon + tablet kullanimi desteklenmiyordu.
--   2) Uygulamayi silmis bir kullanicinin olu token'i hicbir zaman temizlenmiyordu;
--      her bildirim denemesi sonsuza kadar hata uretiyordu.
CREATE TABLE user_device_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    token VARCHAR(512) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Ayni token iki hesaba baglanamaz: cihaz el degistirdiginde eski sahibin
    -- bildirimleri yeni kullaniciya gitmemeli.
    CONSTRAINT uq_user_device_token UNIQUE (token)
);

CREATE INDEX idx_user_device_token_user ON user_device_token(user_id);

-- Mevcut token'lar tasinir; veri kaybi olmaz.
INSERT INTO user_device_token (user_id, token)
SELECT id, fcm_token FROM app_user
WHERE fcm_token IS NOT NULL AND fcm_token <> '';
